### ISSUE TITLE
How to use it to generate multiple js files?

### ISSUE THREAD

**Issue by zhiy** [thheller/shadow-build-example#2]
Is there doc or example use it to generate multiple js files? Like :modules option? I have problems to use modules option, to see whether shallow build can help.

**Comment by thheller** [comment]
If you are using this as a base it is as simple as adding another `configure-module` call.

The signature is `(configure-module module-id module-entries depends-on)` where
`module-id` is a keyword, `module-entries` is a vector of namespace symbols and `depends-on` is a set of other `module-id`.

The modified `build.clj` [1] would looks something like this:

```clojure
(defn project-setup [opts]
  (-> (cljs/init-state)
      (cljs/set-build-options
        {:public-dir (io/file "demo/js")
         :public-path "demo/js"})
      (cljs/set-build-options
        opts)
      (cljs/find-resources-in-classpath)
      (cljs/find-resources "src/cljs")
      (cljs/configure-module :base ['cljs.core] #{})
      (cljs/configure-module :demo ['demo.app] #{:base})
      (cljs/configure-module :other ['demo.other] #{:base})
      ))
```

This builds 3 modules: a `base.js` which contains the common code, `demo.js` which only contains code user by `demo.app` and `other.js` which contains code only used by `demo.other`.


[1] https://github.com/thheller/shadow-build-example/blob/master/src/dev/build.clj
